package rules
 
import com.javainuse.model.Product
import com.javainuse.model.Channel
import com.javainuse.model.ChannelType
rule "Offer for Diamond"
	when 
		productObject: Product(type=="diamond")
	then
		productObject.setDiscount(15);
	end
rule "Offer for Gold"
	when 
		productObject: Product(type=="gold")
	then
		productObject.setDiscount(25);
	end
rule "ITID check"
    dialect "java"
	when
  		channel : Channel(maxRate < 1500 && vendorCategory=="GSV" && vendor=="Any GSV")
  	then
  	    channel.setChannelType(ChannelType.GREEN);
end